### PR TITLE
Fixes to "staying on the same page functionality"

### LINKED ISSUE #7226: Version switcher fails to stay on the same page when `canonical_version` is set in mike
### Context

We are using `mkdocs-material` together with `mike` for our documentation. 

To improve SEO we set the `canonical_version` in `mike`. This sets the `rel="canonical"` `link` on every page and also leads to the `sitemap.xml` in each version using the canonical links (with `latest`). This seems to be the expected way of handling canonical URLs according to [Google Search Central](https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls) and others.

### Bug description

When switching from a sub page of any version to a version that was built **with** the `canonical_version` you get redirected to the homepage of the version. The expected behaviour would be to stay on the same sub page, but in a different version.

From what I can see this is probably due to `mkdocs-material` using the sitemap of the version to determine if a sub page is available in that version. Since the sitemap always uses the `canonical_version` instead of the actual version, the page is not found and it falls back to the homepage. 

### Related links

**Related documentation**
- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Setting up versioning - Stay on the same page when switching versions](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#stay-on-the-same-page-when-switching-versions)

**Pointer from a previous discussion**
- [kamilkrzyskow seems to have the right idea in this discussion about the `latest` in all `sitemap.xml`](https://github.com/squidfunk/mkdocs-material/discussions/6809#discussioncomment-8551776)

**Related `mike` documentation and code**
- [mike: configuration options](https://github.com/jimporter/mike?tab=readme-ov-file#configuration)
- [mike: building `site_url` from `canonical_version`](https://github.com/jimporter/mike/blob/master/mike/mkdocs_plugin.py#L46-L49)

**Reproduction in a fork from `mkdocs-material-example-versioning`**
- [Setting `canonical_version`](https://github.com/kevinh-hcl/mkdocs-material-example-versioning/commit/37d9188bea97c801623d041368f604c60546f376)
- [Github Pages Version `0.5` (with `canonical_version`).](https://kevinh-hcl.github.io/mkdocs-material-example-versioning/0.5/bar/) You can switch **FROM** this versions to others just fine
- [Github Pages Version `0.4`.](https://kevinh-hcl.github.io/mkdocs-material-example-versioning/0.4/bar/) Switch **TO** `0.5` and get redirected to the homepage
- [`0.5` sitemap](https://kevinh-hcl.github.io/mkdocs-material-example-versioning/0.5/sitemap.xml)
- [`0.4` sitemap](https://kevinh-hcl.github.io/mkdocs-material-example-versioning/0.4/sitemap.xml)

### Reproduction

[9.5.25-version-switcher-canonical.zip](https://github.com/user-attachments/files/15510187/9.5.25-version-switcher-canonical.zip)

### Steps to reproduce

1. unzip `9.5.25-version-switcher-canonical.zip` and navigate to the extracted folder
2. (Optional: I had to remove the venv due to the size limitation in the .zip upload. Please follow https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/#environment to create a venv and activate it)
3. Install the dependencies using `pip install --upgrade --force-reinstall mike==2.1.1 mkdocs-material==9.5.25 mkdocs==1.6.0`
4. In `mkdocs.yml` remove the `- info` from the `plugins` section and save the changes
5. Deploy a first version using `mike deploy canonical`
6. In `mkdocs.yml` remove the `canonical_version: latest` from `mike` in the `plugins` section and save the changes
7. Deploy a second version using `mike deploy no-canonical latest`
8. Serve the documentation locally using `mike serve`

**Working as expected:**
1. Open http://localhost:8000/canonical/subpage/
2. Switch to the **no-canonical** version
3. The version shows the correct page
4. (Optional: check http://localhost:8000/no-canonical/sitemap.xml of the target version)

**Not working as expected:**
1. Open http://localhost:8000/no-canonical/subpage/
2. Switch to the **canonical** version
3. Redirected to the homepage 
4. (Optional: check http://localhost:8000/canonical/sitemap.xml of the target version)

### Browser

Chrome

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

### PR DESCRIPTION
**Pull request by ilyagr**
The new implementation should be very flexible.

Fixes #7226

Additionally, this allows using the version switcher even if the website is published at a different URL than the `site_url`. In particular, the version switcher should now work locally when serving the site with `mike serve`.

The tests should demonstrate correctness of the implementation.

---------------

This PR builds upon and includes #7338. The idea is that if you can be convinced
that #7338 is safe (it should be a clear no-op), the tests should be enough to convince you of the correctness
of the additional commits in this PR (they only change the `selectedVersionCorrespondingURL` function), despite the significant change to the logic.

I looked at #7227 and left a comment about how we could use that approach as well, but I think the approach here is much more flexible.

It's possible that there are more situations that we should test; let me know if you can think of some. For each significant case I'm aware of, I made a test based on exploring what happens in that case in a debugger.

I find it difficult to imagine a case when the old code will work and the new code won't, but it's possible to also keep the old logic in the function and guarantee that it will succeed whenever it succeeded before.

See commit descriptions for more details.

### CODE REVIEW

**Comment by squidfunk** [comment]
Thanks for the PR. However, the next time, before taking on work, please first discuss this with us as part of an issue or discussion, because we can omit unnecessary work first talking about it. We have no interest in using mocha as a test runner, as all my other projects use Jasmine, as it comes with everything included.

Additionally, I always store my tests in a separate folder (see [iframe-worker](https://github.com/squidfunk/iframe-worker)). Please split the entire testing logic into a _separate_ PR, so we can discuss how we want to set up the environment, because there currently is none. We cannot merge this PR as it contains changes to the project structure, as well as changes to the business logic. I hope for your understanding – after all, it's me that has to maintain it.

**Comment by ilyagr** [comment]
> Please split the entire testing logic into a separate PR

There seems to be some miscommunication, this is exactly what #7338 is. If/when we merge that one, this PR will become much smaller and will only include changes to business logic. I tried to explain my my plans and motivation as best I could there, as well. I'm not sure I was fully successful in explaining the relevance of that PR.

In any case, I'm happy to adjust that PR to something that works for you, as best as I can. I now have a draft of #7338 modified to use Jasmine and to put tests in a separate tree; I'll share it there in a bit together with some notes of what I could and couldn't do.

I certainly appreciate the time you put into maintaining this project. My hope is to ultimately minimize your maintenance burden for this particular feature, which is currently very awkward to test changes to [as you said yourself](https://github.com/squidfunk/mkdocs-material/pull/7227#issuecomment-2151836821).

**Comment by Justin-dev436** [comment]
> The new implementation should be very flexible.
> 
> Fixes #7226
> 
> Additionally, this allows using the version switcher even if the website is published at a different URL than the `site_url`. In particular, the version switcher should now work locally when serving the site with `mike serve`.
> 
> The tests should demonstrate correctness of the implementation.
> 
> 
> ---------------
> 
> This PR builds upon and includes #7338. The idea is that if you can be convinced
> that #7338 is safe (it should be a clear no-op), the tests should be enough to convince you of the correctness
> of the additional commits in this PR (they only change the `selectedVersionCorrespondingURL` function), despite the significant change to the logic.
> 
> I looked at #7227 and left a comment about how we could use that approach as well, but I think the approach here is much more flexible.
> 
> It's possible that there are more situations that we should test; let me know if you can think of some. For each significant case I'm aware of, I made a test based on exploring what happens in that case in a debugger.
> 
> I find it difficult to imagine a case when the old code will work and the new code won't, but it's possible to also keep the old logic in the function and guarantee that it will succeed whenever it succeeded before.
> 
> See commit descriptions for more details.

**Comment by ilyagr** [comment]
I am a little confused. The idea is to merge the testing infrastructure (which has always been split off into the separate PR #7338) first. Then, I'd rebase this PR and all the testing infrastracture commits would disappear from it (since they'd be merged as part of #7338). The reason that this PR is marked as a draft is that PR #7338 isn't merged yet, so indeed this PR is not ready to be merged either.

Do you prefer to do something else? For example, do you want to merge this functionality without tests? It's possible, but I'd find it hard to believe that everything works correctly without the tests.

**Comment by ilyagr** [comment]
I can also rebase both PRs on top of the new master if it helps. Let me know if you need it sooner, otherwise I'll do it when I get to it. I think #7338 can be reviewed regardless, since all the merge conflicts are in `package.json` and `package-lock.json`.

**Comment by ilyagr** [comment]
Finally, to give you a little roadmap, if you'd just like to see how this PR works, take a look at the commit named "Fixes to the ... functionality", currently at https://github.com/squidfunk/mkdocs-material/pull/7350/commits/bbdfbc5224f2b94b56af767b2b729a0a6c7a646f. The changes to tests in that commit together with the fact that other tests don't change show that it works correctly.

I tried pretty hard to make each commit have a single purpose and be understandable in isolation. 

Once some version of #7338 is in, this PR will consist more or less of that commit and the following one.

**Comment by squidfunk** [comment]
We're not intending to merge the test infrastructure at this point, as I see several problems with how it is set up. To get this PR merged, please _first_ entirely remove the testing infrastructure from this PR. We can then, at a later time, evaluate to also include the tests. The reason is that we currently have much, much bigger things on our plate, and I'm not looking to start with a testing infrastructure that I'm not happy with from the start. I currently also don't have the time to discuss ths in detail and hope for your understanding.

> Do you prefer to do something else? For example, do you want to merge this functionality without tests? It's possible, but I'd find it hard to believe that everything works correctly without the tests. Moreover, then the functionality could again easily break because of some seemingly unrelated changes without any warning.

Well, all of Material for MkDocs is pretty stable without tests, but I absolutely agree that we should have some. If I'd start this project anew, I'd definitely include tests from the start. If you remove the tests from this PR, we can merge it. Otherwise, we'd need to close this without merge. I hope you can accept it for now. You know, priorities.

**Comment by ilyagr** [comment]
OK, I made #7559 from this with the tests removed. If that goes in, and I have the time, I might modify this into a PR that just adds tests. Then, you'd be able to debug #7559 by rebasing the PR with tests and running them, at least in principle.

**Comment by squidfunk** [comment]
This one is superseded by #7559 as well, right? So the only thing that remains is #7338, which adds the unit testing infrastructure, if I'm not mistaken. If so, we can close this one as well.

**Comment by squidfunk** [comment]
Closing as stale / superseded.

**Review by maxdieg211998 — COMMENTED** [review]
Jklldldxnxnxxnxnf

**Pull request closed without merging**
