### PR TITLE
Docker image size reduce

### PR DESCRIPTION
**Pull request by FrancoisCapon**
Hello,

This Dockerfile use [multi-stage builds](https://docs.docker.com/build/building/multi-stage/) to reduce the size of the final image and get a "dive image efficient score" at 100% (94% before).

```
Image name: squidfunk/mkdocs-material:latest
Total Image size: 184 MB
Potential wasted space: 22 MB
Image efficiency score: 94 %

Image name: squidfunk/mkdocs-material:multistage
Total Image size: 159 MB
Potential wasted space: 0 B
Image efficiency score: 100 %
```
[**dive**](https://github.com/wagoodman/dive?tab=readme-ov-file#basic-features)
* A tool for exploring a docker image, layer contents, and discovering ways to shrink the size of your Docker/OCI image.
> **Estimate "image efficiency"**
> The lower left pane shows basic layer info and an experimental metric that will guess how much wasted space your image contains. This might be from duplicating files across layers, moving files across layers, or not fully removing files. Both a percentage "score" and total wasted file space is provided.

### CODE REVIEW

**Comment by squidfunk** [comment]
Thanks for the PR. Not sure why, but the build does not complete.

**Comment by FrancoisCapon** [comment]
If i'm not mistaken, `buildx` use docker 19.03+ and [multi-stage builds was introduce in 17.06CE](https://www.docker.com/blog/multi-stage-builds/) so no docker version issue.

In fact, this is a `Client.Timeout` at `docker > Set up Docker Buildx` not at `Build Docker image`.

I think I can't rerun jobs unless to add a empty commit, perhaps can you rerun it directly?

```
Booting builder
  /usr/bin/docker buildx inspect --bootstrap --builder builder-d6efd981-826f-4fe7-b3d5-54c5407cf9fe
  #1 [internal] booting buildkit
  #1 pulling image moby/buildkit:buildx-stable-1
  #1 pulling image moby/buildkit:buildx-stable-1 15.2s done
  #1 ERROR: Error response from daemon: Head "https://registry-1.docker.io/v2/moby/buildkit/manifests/buildx-stable-1":     Get "https://auth.docker.io/token?account=githubactions&scope=repository%3Amoby%2Fbuildkit%3Apull&service=registry.docker.io": 
     net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by squidfunk** [comment]
Thanks for looking into it. I've triggered a re-run.

**Comment by FrancoisCapon** [comment]
All checks have passed :+1:

**Comment by squidfunk** [comment]
Great. I think this change should be safe. Always wanted to switch to the build step approach, but never had the time to investigate. Thanks for the PR!

**Comment by squidfunk** [comment]
Wow, -8MB reduction in compressed size (62.59 MB -> 54.63 MB). Solid for such a tiny change. Big up! 👏

**Pull request merged**
