### PR TITLE
Fix buggy header shadow

### PR DESCRIPTION
**Pull request by PegasisForever**
Fix issue: #2488

Explained in this comment: #2488 (comment)

### CODE REVIEW

**Comment by squidfunk** [comment]
Thanks for investigating. So, in the end, it's only a rounding error, right?

**Comment by PegasisForever** [comment]
Ya it's just a rounding error, my code works with tabs and announcement bar, tested on the official docs site.

**Comment by squidfunk** [comment]
Thanks for the PR and your investigation. It's definitely related to rounding errors. However, the fix doesn't solve the issue in its entirety. When I zoom out, the header shadow is still not visible with your fix applied. The problem stems from the fact that `getElementSize` uses the `offsetWidth` and `offsetHeight` properties, while `watchElementSize` returns `DOMRect` objects. The former is the effective size as rendered (thus, no floating point values), the latter what has been computed during layout calculation (floating point values).

We definitely need to make those computations consistent, but we can't just use `Math.round`, because [different browsers round differently](https://cruft.io/posts/percentage-calculations-in-ie/), so the behavior would not be consistent.

**Comment by squidfunk** [comment]
Superseded by f43ef69ee – I fixed the root cause.

**Pull request closed without merging**
