### PR TITLE
WIP – Tutorials preview

### PR DESCRIPTION
**Pull request by squidfunk**
This is the preview for the tutorials section we're currently working on, see #1573

### CODE REVIEW

**Comment by Andre601** [comment]
I saw that there is now a tutorial on adding own icons.
I think it would beneficial to mention which name-spaces (folder) are already use by Material to prevent possible confusion and accidental overriding of icons (if that would even be possible)

**Comment by squidfunk** [comment]
It's possible as of the latest beta of mkdocs-material-extensions, but were waiting for the final release. You can, however, submit a PR already if you like.

**Comment by facelessuser** [comment]
Yeah, I haven't really received any feedback on the last beta. But I guess if I hear nothing, the new custom icons must be working.

**Comment by Andre601** [comment]
I just found out, that you could use `github-actions[bot]` as `user.name` and `41898282+github-actions[bot]@users.noreply.github.com` as `user.email` for git and perhaps even manually push changes to the gh-branch.
I don't even know if a PAT would be nessesary for the GitHub action of if you could just use the `${{ github.ACTOR }}` (or how it was called) instead.
Would for sure make some things easier as you don't need to manually create a PAT first.

I also found out on github.community, that the checkout action already sets the repository up with the GitHub one as remote, so is adding a remote really needed? Because otherwhise could we leave this away.

I'm thinking about reworking the tutorial but first would like to get some feedback from your side on this, as I'm not that well with Git, GitHub and GitHub Actions.

**Comment by squidfunk** [comment]
If adding the remote is not needed after `checkout`, which I assume is mandatory for doing anything at all, it can surely be dropped from the docs.

**Comment by diba1013** [comment]
> Yeah, I haven't really received any feedback on the last beta. But I guess if I hear nothing, the new custom icons must be working.

Sorry for that, I have been busy in the last week with other stuff and not monitoring the repos that much. However, I checked that the betas for the icons is working before I proposed the final changes to my PR. Still haven't gotten around to propose small fixes for that...

**Comment by Andre601** [comment]
The entry in the navigation seems to be missing for GitLab

**Comment by Andre601** [comment]
Not sure how useful or important that would be, but I created a Template repository for people who want to quickly create a MkDocs Doc on GitHub.
https://github.com/Andre601/mkdocs-template

(Don't ask me why I post this here)

**Comment by Andre601** [comment]
Something that came to mind: Maybe a community section somewhere (Maybe not as its own tab but nested in one of the other sections?
It would be essentially a collection of community-driven parts for the Material theme, like custom CSS or JavaScript, extensions(?) or setups.

Not sure tho, as this could also be seen bloat towards the entire project.

**Comment by squidfunk** [comment]
> Something that came to mind: Maybe a community section somewhere (Maybe not as its own tab but nested in one of the other sections?)

I'm eagerly waiting for GitHub discussions coming out of beta. Maybe I'm blind, but I haven't found a site where I could submit this project for the beta. Discussions would be the ideal place to share common extensions that are out of scope for this project.

**Comment by Andre601** [comment]
It is in public beta soon, meaning it will be added soon, but I assume you have to enable it, similar to things like GitHub Sponsors.

**Comment by squidfunk** [comment]
There's yet no checkbox I can enable in the settings of this repository. I tweeted them:
https://twitter.com/squidfunk/status/1260102756410548224

**Comment by Andre601** [comment]
I assume that it either isn't rolled out yet, or it gets rolled out slowly.

**Comment by squidfunk** [comment]
Two things:

1. heard back from GitHub - unfortunately, we‘ll not going to be part of the discussions beta at this point. Maybe in or after the summer.

2. After getting dark mode out the door, the next thing on my list is a restructuring of the docs, so they give more guidance. I’ll revisit this PR and integrate all of your amazing work in this process. There’s likely not going to be a dedicated tutorials section, but everything is going to be blend into a user guide. My current idea is to split stuff into a user guide (usage and configuration) and a developer guide (extension and customization)

**Comment by squidfunk** [comment]
I started rewriting the docs in #1735. __Getting started__ will be broken into multiple pages, as it's too long in general and too brief for some subsections. I will merge the GitLab and GitHub tutorials into a new page called __Deploying your site__ and the icons tutorial into a guide called __Adding and using icons__.

This is an ongoing process and may take from weeks to months.

**Comment by squidfunk** [comment]
I integrated the GitHub and GitLab guides into the [deploying your site](https://deploy-preview-1735--mkdocs-material-preview.netlify.app/getting-started/publishing-your-site/) guide. I tried to keep it as concise as possible and provided a minimal configuration. Thanks again for writing everything up, it made the work so much easier!

**Comment by squidfunk** [comment]
Integrated the tutorial to [add additional icon sets](https://deploy-preview-1735--mkdocs-material-preview.netlify.app/setup/changing-the-logo-and-icons/#additional-icons). Again, I tried to keep things as concise as possible. The docs are already rather longish, so let's see if this is explanatory enough.

Thanks again for helping out on the tutorials! If you feel that something crucial is missing, feel free to add a comment in #1735. Also, any feedback is appreciated.

**Pull request closed without merging**
