### PR TITLE
Fix disqus breaks when instant loading enabled

### PR DESCRIPTION
**Pull request by PegasisForever**
Use [DISQUS.reset](https://help.disqus.com/en/articles/1717163-using-disqus-on-ajax-sites) to update disqus section when navigating to other pages.

### CODE REVIEW

**Comment by squidfunk** [comment]
Thanks for the PR! What happens when coming from a page with Disqus to a page without? Is `DISQUS.reset` a no-op?

**Comment by PegasisForever** [comment]
If a page doesn't have disqus, the disqus partial won't be in the html, so the code won't be there and will not run.

Also, I wonder is there a "proper" way to check if the page is loaded by instant loading? (like an event or something), checking `document
readyState` feels like a hack.

**Comment by squidfunk** [comment]
Yes there is:

```
document$.subscribe(function() {
  ...
})
```

The `document$` observable will emit on initial load, and on every subsequent load when using instant loading.

**Comment by squidfunk** [comment]
Superseded by e71b12943. This PR has become stale, so I decided to take the lead here. I could simplify the code a little, and we now have a working Disqus / instant loading integration. Thanks again for your work!

**Comment by squidfunk** [comment]
Released as part of 7.3.1.

**Pull request closed without merging**
