### PR TITLE
Minor documentation updates

### PR DESCRIPTION
**Pull request by brendo**
Hope you don't mind, but I thought this might pay forward in some small way to #46!

- Removed reference to `bower` as it's no longer part of the process
- Couple of newlines as per `.editorconfig`

### CODE REVIEW

**Comment by squidfunk** [comment]
Thanks you for your contribution, however personally I think that prepending the $ breaks the ability to simply copy and paste the commands and removing the # breaks the syntax highlighting, so sorry, I'm not a fan.

Regarding the newlines: yes, those should be included in the files and where missing in my editor (clumsy me). I have a rewrite of the documentation on my list as a lot of stuff changed :-)

**Comment by brendo** [comment]
No worries! Would you prefer I pair this PR back to just focus on the `bower` and newlines or simply close it?

**Comment by squidfunk** [comment]
@brendo would be awesome, then I could merge it directly.

**Comment by brendo** [comment]
Done :+1:

**Pull request merged**
