### PR TITLE
top.title localization was missing in ru.html

### PR DESCRIPTION
**Pull request by arterm-sedov**
The "Back to top" button was displaying in English in the Russian theme

### CODE REVIEW

**Comment by squidfunk** [comment]
Thanks! Could you also provide the translations for the other missing keys? The best idea is to check which translations are missing from `en.html`:

https://github.com/squidfunk/mkdocs-material/blob/ff4cf19f8d72234945251001006d9acbf1541e22/src/partials/languages/en.html#L24-L60

**Review by squidfunk — CHANGES_REQUESTED** [review]
Please also provide the other missing translations.

**Comment by arterm-sedov** [comment]
> Please also provide the other missing translations.

Will do a bit later. Thanks for the hint.

**Comment by arterm-sedov** [comment]
> Thanks! Could you also provide the translations for the other missing keys? The best idea is to check which translations are missing from `en.html`:
> 
> https://github.com/squidfunk/mkdocs-material/blob/ff4cf19f8d72234945251001006d9acbf1541e22/src/partials/languages/en.html#L24-L60

Sure, I will translate them

**Comment by arterm-sedov** [comment]
I've committed the requested changes in a new pull-request today

**Comment by squidfunk** [comment]
Thanks! Superseded by #3298.

**Pull request closed without merging**
