### PR TITLE
Fix-up site_url (link behind home button) for usage from file://

### PR DESCRIPTION
**Pull request by ktomk**
Fix in 454339b only works on base directory level, pages in subdirectories
were still broken.

Similar patch for url filter in mkdocs/mkdocs#2202.

Ref: 454339bd359b8708aaf1b2cfb22098b158d475d3

### CODE REVIEW

**Comment by squidfunk** [comment]
Could you please provide a config for reproduction/testing? I'd like to test it before merging.

**Comment by ktomk** [comment]
A simple way to test it is to blank the site_url in mkdocs.yml and build with --no-directory-urls.

Visiting the "Setup" section (or any other section in sub-directory within docs) shows the index.html is not added on the site link in the header.

With the fix applied, it shows it.

I add a TEST commit on top, please don't merge it, is shows this more boldly.

**Comment by squidfunk** [comment]
I've had some time to investigate and must say - that's a pretty elegant solution! I've used your technique in 48b4120b, as I couldn't merge the PR, because it's missing the built files in the `material` folder (see [this guide](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md#submitting-a-pull-request-pr)). Closing this, as the linked commit supersedes this PR. Thanks again for your time!

**Comment by ktomk** [comment]
@squidfunk Ack, works for me.

**Pull request closed without merging**
