### PR TITLE
Add md-tabs__item--active

### PR DESCRIPTION
**Pull request by SoumayaMauthoorMOJ**
Create a class for the active item in the tab

See https://github.com/squidfunk/mkdocs-material/discussions/5048

Sorry it took so long!

### CODE REVIEW

**Comment by SoumayaMauthoorMOJ** [comment]
I made the minimum changes but I could rename `class` to `link_class` so that it follows the same pattern as `item_class`?

**Comment by SoumayaMauthoorMOJ** [comment]
@squidfunk is there anything else I need to add to this PR ? I followed the instructions to build the theme and commit the compiled output

**Comment by squidfunk** [comment]
@SoumayaMauthoorMOJ haven't had time yet, I'm sorry. I'll tackle it asap 😬

**Comment by SoumayaMauthoorMOJ** [comment]
Thanks @squidfunk no rush since I have a work-around in place but good to know still in the running :-)

**Comment by squidfunk** [comment]
Note that this is part of #5683, i.e., the branch that contains Material for MkDocs 9.2.0 with all features from the latest funding goal. It will first be available as a beta release.

**Comment by SoumayaMauthoorMOJ** [comment]
Perfect thank you :-)

**Pull request closed without merging**
