### PR TITLE
Add rss plugin to Dockerfile

### PR DESCRIPTION
**Pull request by ericdallo**
At https://emacs-lsp.github.io/lsp-mode we use the docker image and want to add rss support

### CODE REVIEW

**Comment by squidfunk** [comment]
Thanks for the PR, however the plugin doesn’t look like it’s very popular (very few stars), so I think at the current moment it’s not worth increasing the size of the Docker image.

**Comment by ericdallo** [comment]
That's sad, so emacs-lsp would need to stop using the docker image and setup mkdocs-material manually [here](https://github.com/emacs-lsp/lsp-mode/blob/master/.github/workflows/docs.yml#L34)?

**Comment by squidfunk** [comment]
No, you can continue to use the Docker image by extending it and adding the plugins you need:

``` docker
FROM squidfunk/mkdocs-material
RUN pip install ... whatever you need
```

In fact, I'm thinking about removing all plugins from the Docker image, as more and more requests for individual plugins are coming up and we cannot bundle everything.

**Comment by squidfunk** [comment]
I added [a guide](https://squidfunk.github.io/mkdocs-material/getting-started/#with-docker) how to install plugins in the Docker image in e0b53999. Closing this PR for the reasons stated. If in the future, this PR gets many upvotes, we can bundle the RSS plugin, but for now, you seem to be the only one using it.

**Comment by ericdallo** [comment]
It makes sense, thanks for the explanation @squidfunk, I'll do that :)

**Pull request closed without merging**
