### PR TITLE
Serbian latin translation

### PR DESCRIPTION
**Pull request by majkinetor**

### CODE REVIEW

**Comment by squidfunk** [comment]
Thanks! Is this a valid HTML5 language code?

**Comment by majkinetor** [comment]
Thats what I wanted to ask but decided not to :) It looks like its not:

https://gist.github.com/JamieMason/3748498#file-html-languages-txt-L192

It looks like `sr` should be latin (or `sr-Latn-CS`) and cyrlic that is currently `sr` should be `sr-Cyrl-CS`

What should I do ?

**Comment by majkinetor** [comment]
Oh, there is already `sh` here. I'll just close this. Sorry :)

**Comment by squidfunk** [comment]
No worries, sometimes hard to keep track what we already have 😉

**Pull request closed without merging**
