### PR TITLE
small improvements and a correction

### PR DESCRIPTION
**Pull request by niclasheinz**
Changes:

- Fixes line highlighting in [codeblock](https://squidfunk.github.io/mkdocs-material/tutorials/blogs/basic/#pinning)
- Update trusted by users count in [philosophy](https://squidfunk.github.io/mkdocs-material/philosophy/), because it's outdated
- Add a small thing to "Works on all devices"  in [philosophy](https://squidfunk.github.io/mkdocs-material/philosophy/)

### CODE REVIEW

**Comment by squidfunk** [comment]
Thanks! Actually, the texts are not synced with the latest versons on the README. Same goes for the landing page texts in Insiders. Also, we're calculating with 50,000 users, since it's 55,000 proiects + a lot of projects inside companies, so 50k is a conservative estimate. Could you maybe also synchronize the texts on the landing page and the philosophy page as well? You can take the README as the source of truth. We really need to deduplicate those at some point.

**Comment by niclasheinz** [comment]
I'll get it done later today.

**Comment by niclasheinz** [comment]
I've adopt the text in philosophy from README

**Comment by squidfunk** [comment]
Perfect, thank you!

**Pull request merged**
