### PR TITLE
Fix broken screenshots and link in documentation

### PR DESCRIPTION
**Pull request by daaf**
This is a fix for two issues I observed in the documentation.

- On **Setup > Setting up navigation > Hide the sidebars**, the _Hide navigation_/_Hide table of contents_/_Hide both_
screenshots were either broken or showing an incorrect image.
- On **Reference** > **Admonitions** > **Customization** > **Custom admonitions**, the "You can even add animations" link was giving a 404

### CODE REVIEW

**Comment by daaf** [comment]
Realized my Prettier added a bunch of trivial formatting changes. Will fix and re-open.

**Comment by daaf** [comment]
Errr...I though I was following the submission guidelines by committing everything in the "material" directory, but now seeing the number of files and lines of code changed, I'm not so sure. Please let me know if I need to do something differently.

**Comment by polarathene** [comment]
You should remove the content you accidentally committed with SVG generated assets in `.icons/` which is unrelated to your PR.

The problem this PR resolves could be better avoided from repeating if using text references instead of numbers (which aren't as pleasant to manage imo).

**Comment by daaf** [comment]
Reverted the unrelated changes in `.icons/`.

**Comment by squidfunk** [comment]
Thanks!

**Pull request merged**
