### PR TITLE
Updated Croatian translations

### PR DESCRIPTION
**Pull request by vedranmiletic**

### CODE REVIEW

**Comment by squidfunk** [comment]
Thanks!

**Comment by vedranmiletic** [comment]
Sorry, just noticed the patch might be missing a comma after `"toc.title": "Sadržaj"`. Please check.

**Comment by squidfunk** [comment]
I fixed that in a subsequent commit. Changes have been released with 8.4.1.

**Comment by vedranmiletic** [comment]
Great, thanks!

**Pull request merged**
