### PR TITLE
Add CSS variables for Mermaid sequence diagrams

### LINKED ISSUE #5824: Mermaid: allow customizing sequence diagram notes node style
### Context

The color of Mermaid sequence diagram notes looks a bit off IMO (see, e.g., https://squidfunk.github.io/mkdocs-material/reference/diagrams/#using-sequence-diagrams), at least not as nicely integrated with the rest of the theme colors.

### Description

[`mkdocs-material` overrides some Mermaid colors with own CSS variables](https://github.com/squidfunk/mkdocs-material/blob/9.1.21/src/assets/javascripts/components/content/code/mermaid/index.css) but not the "note" node. How about introducing new CSS variables, e.g. `--md-mermaid-note-bg-color` as the fill color and `--md-mermaid-note-fg-color` as the stroke color ([consistent with existing naming](https://github.com/squidfunk/mkdocs-material/blob/9.1.21/src/assets/javascripts/components/content/code/mermaid/index.css#L33-L34)), and add an override for Mermaid's `note` CSS class? The default colors could be based on the [info admonition color](https://github.com/squidfunk/mkdocs-material/blob/9.1.21/src/assets/stylesheets/main/extensions/markdown/_admonition.scss#L32).

There exists some [customization for note _text_](https://github.com/squidfunk/mkdocs-material/blob/9.1.21/src/assets/javascripts/components/content/code/mermaid/index.css#L359-L368), so perhaps not customizing the note rect itself was an oversight.

### Related links

- [Using sequence diagrams](https://squidfunk.github.io/mkdocs-material/reference/diagrams/#using-sequence-diagrams)

### Use Cases

Having a nicely integrated Mermaid diagram makes documentation more pleasant to read. It's mostly good already, but sequence diagram notes look a bit off.

### Visuals

_No response_

### Before submitting

- [X] I have read and followed the [change request guidelines](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/).
- [X] I have verified that [my idea is a change request and not a bug report](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#its-not-a-bug-its-a-feature).
- [X] I have ensured that, to the best of my knowledge, [my idea will benefit the entire community](https://squidfunk.github.io/mkdocs-material/contributing/requesting-a-change/#benefit-for-the-community).
- [X] I have included relevant links to [the documentation](https://squidfunk.github.io/mkdocs-material), related [issues](https://github.com/squidfunk/mkdocs-material/issues), and [discussions](https://github.com/squidfunk/mkdocs-material/discussions) to underline the need for my idea.

### PR DESCRIPTION
**Pull request by sisp**
I've added CSS variables for Mermaid sequence diagrams to ease customization. I've also improved the note style to align better with the rest of the theme. Except for the note style, all other CSS variables use the previous styles as defaults.

The rationale of the CSS variables is this:

* Each sequence diagram component has its own namespace `--md-mermaid-sequence-<component>-*`.
* `*-fg-color` maps to text color &ndash; seems consistent with existing variable names
* `*-bg-color` maps to shape background color (`fill`)
* `*-border-color` maps to shape border color (`stroke`)
* `*-line-color` maps to line color (typically `stroke`, `fill` for arrowhead)

I've added a commit for each component to make the changes per component easier to check.

WDYT, @squidfunk @nejch?

Resolves #5824.

### CODE REVIEW

**Comment by squidfunk** [comment]
Thanks for the PR! Skimming through the PR, my first reaction is: looks really good! I'll review this PR in the coming days, so we can quickly merge it. Then, we should do the same for all other diagram types ☺️ Would you like to work on this as well?

**Comment by sisp** [comment]
Sounds great! Sure, once you've approved this approach, I can apply it to the other diagram types as well.

**Comment by squidfunk** [comment]
Looks great! We'd be happy to accept PRs for the other diagram types as well ☺️

**Comment by squidfunk** [comment]
Note that for now, we'll not going to advertise it on the docs, because I'm not yet entirely sure about the naming conventions. We _might_ change the naming a little in the end, but for that to know we need the other types. Always better to decide when you see the whole picture. However, we'll ship it now with 9.2.7.

**Pull request merged**
