### PR TITLE
Remove outdated comment now that GitHub has caught up

### PR DESCRIPTION
**Pull request by jeffwidman**
This is no longer necessary: https://github.com/orgs/community/discussions/6456#discussioncomment-5244057

### CODE REVIEW

**Comment by squidfunk** [comment]
Nice! This means we can remove `setup.py`, right?

**Comment by jeffwidman** [comment]
Yes, I hadn't done that as you currently have it setup as a warning file, but if you prefer I can delete it entirely... I know I'd prefer to do that!

**Comment by squidfunk** [comment]
Let's get rid of it, as it has no purpose anymore 🧹

**Comment by jeffwidman** [comment]
💥

**Comment by squidfunk** [comment]
Perfect, thanks for your time!

**Pull request merged**
