### PR TITLE
Add mkdocstrings JSON schema

### PR DESCRIPTION
**Pull request by pawamoy**
I've pushed schemas for mkdocstrings, mkdocstrings-python and Griffe (referencing each other in this order).
The tool you mentioned (https://www.jsonschemavalidator.net) validates the schemas, however it seems to have no issue with additional properties that do not exist, while I explicitly added `"additionalProperties": false` to the schemas :thinking: 
It also seems to accept wrong types, so not sure if I did something wrong.

Anyway, that's a first draft.

How would I test if this works as expected?

Reference: https://github.com/mkdocstrings/mkdocstrings/issues/488

### CODE REVIEW

**Comment by squidfunk** [comment]
Thanks for the PR! Can you give example input that passes and one that fails? I'd like to check the schema locally before merging to make sure that it works.

**Comment by pawamoy** [comment]
Of course. I noticed I forgot a few things in the schema for mkdocstrings-python, so I'll fix that first and post valid/invalid inputs then :slightly_smiling_face:

**Comment by pawamoy** [comment]
### Valid inputs:

```yaml
- plugins:
  - mkdocstrings
```

```yaml
- plugins:
  - mkdocstrings:
      default_handler: python
      custom_templates: docs/templates
      enable_inventory: false
```

```yaml
- plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [str]
          import:
          - https://example.com
          - url: https://example.com
            base_url: https://example.com
```

```yaml
- plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google  # or numpy, or sphinx
            docstring_options:
              ignore_init_summary: false
              trim_doctest_flags: false
            show_root_heading: false
            show_root_toc_entry: false
            show_root_full_path: false
            show_root_members_full_path: false
            show_object_full_path: false
            show_category_heading: false
            show_if_no_docstring: false
            show_signature: false
            show_signature_annotations: false
            separate_signature: false
            line_length: 60
            merge_init_into_class: false
            show_source: false
            show_bases: false
            show_submodules: false
            group_by_category: false
            heading_level: 2
            members_order: alphabetical  # or source
            docstring_section_style: table  # or list, or spacy
            members: false
            filters:
            - string
            - string
            annotations_path: brief  # or source
```

```yaml
- plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            members:
            - name
            - name
```

### Invalid inputs

```yaml
- plugins:
  - mkdocstrings:
      unknown_property: 0
```

```yaml
- plugins:
  - mkdocstrings:
      handlers:
        python:
          unknown_property: 1
```

```yaml
- plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            unknown_property: yo
            docstring_style: blarg
            docstring_options:
              unknown_property: hey
            members_order: blerg
            docstring_section_style: blurg
            annotations_path: blorg
```

**Comment by squidfunk** [comment]
Perfect, LGTM!

**Pull request merged**
