### PR TITLE
Fixing The Bold Code Block Issue

### PR DESCRIPTION
**Pull request by Mehran-Baghi**
046ef9f will fix the #455 .
It seems that the problem was enforcing the code font-weight to be 400 [here](https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/stylesheets/base/_typeset.scss#L49).
Loading another google font weight is not necessary.
I have built the theme successfully.

### CODE REVIEW

**Comment by Mehran-Baghi** [comment]
I'm not a web developer but I think we should get rid of `font-family` definitions in the `_typeset.scss` since we have already defined them in the `base.html`

**Comment by Mehran-Baghi** [comment]
Also shouldn't we activate the [`font-feature-settings`](https://github.com/squidfunk/mkdocs-material/blob/master/src/assets/stylesheets/base/_typeset.scss#L37) by following them with either `1` or `on`? [Refrence](https://css-tricks.com/almanac/properties/f/font-feature-settings)

**Comment by squidfunk** [comment]
The `font-family` definitions inside `_typeset.scss` are the defaults. If you set `extra.font = false`, the font is not defined inside `base.html`, so there needs to be a default definition. Also we have to check thoroughly if removing the font-weight completely does not cause any issues.

**Comment by squidfunk** [comment]
Regarding the `font-feature-settings`: it's perfectly valid, [see](https://developer.mozilla.org/de/docs/Web/CSS/font-feature-settings)

**Comment by squidfunk** [comment]
Fixed bold code in #458

**Pull request closed without merging**
