### PR TITLE
Rewrite tags documentation

### PR DESCRIPTION
**Pull request by squidfunk**
This branch includes a rewrite of the tags documentation, given the new capabilities of the tags plugin.

### CODE REVIEW

**Comment by DanielHabenicht** [comment]
You might want to fix this small typo while rewriting: 
https://github.com/squidfunk/mkdocs-material/blob/246266fafad2c2fdc78022c14f7f4b2df91167f3/docs/plugins/tags.md?plain=1#L558 
As it should probably mean `tags:`

**Comment by Xocotet** [comment]
Will this update provide a sort by tag-name capability as requested [here](https://github.com/squidfunk/mkdocs-material/discussions/5612)?
Is there an estimated availability date for this?

**Comment by squidfunk** [comment]
This is already available in [Insiders](https://squidfunk.github.io/mkdocs-material/insiders/) via [`listings_sort_by`](https://squidfunk.github.io/mkdocs-material/plugins/tags/#config.listings_sort_by), e.g.:

```
plugins:
  - tags:
      listings_sort_by: !!python/name:material.plugins.tags.item_title
```

You can also provide a custom comparison function.

**Comment by squidfunk** [comment]
I'm closing this PR, since we're not planning to move forward in this specific way. We're currently in the midst of a pretty big restructuring of our documentation, and it's just too early to consider for collaboration on new tags documentation. 

@alexvoss you might consider using the diagrams in a tutorial, if they fit in the flow 😉

**Pull request closed without merging**
