### PR TITLE
Merged features tied to 'Goat's Horn' funding goal

### PR DESCRIPTION
**Pull request by squidfunk**
This PR contains all features that are tied to the [Goat's Horn](https://squidfunk.github.io/mkdocs-material/insiders/#14000-goats-horn) funding goal, which we just reached:

- [Privacy plugin](https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/)
- [Card grids](https://squidfunk.github.io/mkdocs-material/reference/grids/)
- [Tooltips](https://squidfunk.github.io/mkdocs-material/reference/tooltips/)
- [Content tabs: anchor links](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/#anchor-links)
- [Automatic light / dark mode](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#automatic-light-dark-mode)
- [Document contributors](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-contributors)

❤️ ❤️ ❤️ 

Thanks again to all of our awesome sponsors for making our work on this project sustainable! __Without you, all of those features would not exist__. We hope for your continued support, as it allows us to ship more useful and unique features, like for example the projects plugin, which allows to [build multiple MkDocs projects together](https://squidfunk.github.io/mkdocs-material/plugins/projects/).

__If you're a heavy user of Material for MkDocs, consider [sponsoring @squidfunk](https://github.com/sponsors/squidfunk), so we can make this project even more useful in the future and keep it in good shape! In 2023, I've started to build a small team around me and must rely on the financial support by our sponsors so we can keep up with the insane growth of the project and provide support to each of you!__

### CODE REVIEW

**Comment by fghaas** [comment]
@squidfunk Just a small note, you *may* want to choose to make the inclusion of authors' email addresses configurable, as it previously was when using the `git-authors` plugin (per [the current state of the documentation](https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#document-authors), no such option exists — the author's name is always in a `mailto:` link). 

Please see https://github.com/timvink/mkdocs-git-authors-plugin/pull/66#pullrequestreview-1161175682 for a related discussion on author privacy, and also https://github.com/citynetwork/docs/pull/255 for considerations on external link checking.

The current situation is rather awkward because a user can include the following snippet in their configuration:

```yaml
plugins:
  - git-authors:
      enabled: true
      show_email_address: false
```
... and then assume that email addresses would be suppressed, but they are not.

**Comment by squidfunk** [comment]
Thanks for noting. I wasn't aware of this option, maybe it was added after we did the initial integration. Would you like to propose a PR for this? I guess it's only a simple switch in the partial that renders the authors.

**Comment by fghaas** [comment]
I can have a go at that; would I be able to use the same logic [as in the PR I submitted to the `git-authors` plugin](https://github.com/timvink/mkdocs-git-authors-plugin/pull/66/commits/9c24c266b12b359318272f762c8da2024fc98888#diff-05c45f363d65d1c80b31ab871eb67993b6061086fb47085a1830ea6249aa80dcR61)?

**Comment by fghaas** [comment]
Draft PR is in #6494; let me know if that's the right way to go.

**Pull request merged**
