### PR TITLE
const instead of var for redirect script

### PR DESCRIPTION
**Pull request by Stanzilla**
Use const instead of var, the other style changes actually match your stylelint config.

### CODE REVIEW

**Comment by squidfunk** [comment]
It's true that we want to support only modern browsers but I would rather just leave it as a `var` definition. There's no downside, as it's in the global scope anyway and the redirect happens instantly.

**Comment by Stanzilla** [comment]
I really only did the PR because my linter complained :D And I'm still using your stylelint file from master, so feel free to just close if not wanted

**Comment by squidfunk** [comment]
We should add all distribution files to `.stylelintignore` 😉

**Comment by squidfunk** [comment]
Closing for the reasons stated.

**Comment by Stanzilla** [comment]
I'm using ESLint, yeah :)

**Pull request closed without merging**
