### PR TITLE
Tweak CI config

### PR DESCRIPTION
**Pull request by XhmikosR**
* add the `CI` environment variable; removes npm postinstall messages
* move Node.js and Python versions to environment variables
* add the Node.js and Python versions in cache filenames

### CODE REVIEW

**Comment by squidfunk** [comment]
LGTM.

**Comment by XhmikosR** [comment]
One thing I notice @squidfunk is that the deploy action runs for [forks](https://github.com/XhmikosR/mkdocs-material/commits/gh-pages) too. I will make a PR to change this so that it only runs for your repo.

**Comment by squidfunk** [comment]
Consider that some forks may want this and/or rely on this.

**Comment by XhmikosR** [comment]
OK, let's leave it as is then.

**Pull request merged**
