### PR TITLE
Use of document$ observable

### PR DESCRIPTION
**Pull request by alexvoss**
Added tip about using the `document$` observable to ensure the DOM is fully loaded. Hope I got the details right and that this is sufficient to give people the leg up they will need. One thing I am not sure about is whether we need to / should add a note about ordering of the invocations of the callback - or any other fatal assumptions people might make?

### CODE REVIEW

**Comment by alexvoss** [comment]
Not sure why the commit re vim backup files ended up in this? That change is already in the master. I did sync my fork and pulled from it before making today's changes and committing them to a new branch.

**Comment by squidfunk** [comment]
Did you also merge master into this `observable` branch?

**Comment by alexvoss** [comment]
It is possible I was on the `gitignore` branch that I still have locally. So, I might have pulled with no effect on master. Got to remember to delete local branches when deleting them on GitHub! I seem to remember there is a way to delete a branch on GitHub from the command line. I need to script this stuff - just don't do this often enough and been working on some completely unrelated things over the weekend...

**Comment by squidfunk** [comment]
Thanks, LGTM!

**Comment by squidfunk** [comment]
I changed the title of the box to make it clearer. "Make sure the page is fully loaded" is not actionable enough, because IMHO, it's easier to anchor the user at what she wants to do, i.e., integrate a third-party library. Additionally I changed the wording of the demo integration to be a little nicer - IMHO "whatever" is not a really nice word 😉

**Pull request merged**
