### PR TITLE
Fix `versions.json` URL construction with path prefix builds

### LINKED ISSUE #6123: Version selector not shown for builds with path prefix
### Context

_No response_

### Bug description

When serving the site with a path prefix (with [`site_url`](https://www.mkdocs.org/user-guide/configuration/#site_url) configured or by serving the site from a parent directory), the version selector isn't shown and fetching `versions.json` fails with HTTP status 404. The reason is an incorrect URL construction for `versions.json`

https://github.com/squidfunk/mkdocs-material/blob/c928e03fa8d725655c8fe2798c7e810dd3fa2fa8/src/templates/assets/javascripts/integrations/version/index.ts#L76

where `config.base` corresponds to [`base_url`](https://www.mkdocs.org/dev-guide/themes/#base_url)

https://github.com/squidfunk/mkdocs-material/blob/c928e03fa8d725655c8fe2798c7e810dd3fa2fa8/src/templates/base.html#L396

which

> [...] provides relative path to the root of the MkDocs project.

so

`../versions.json` relative to `base_url` resolves to the wrong path. It should be

```diff
-new URL("../versions.json", config.base) 
+new URL("versions.json", config.base) 
```

instead.

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
- [Setting up versioning](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning)

### Reproduction

[9.4.3-mike-path-prefix.zip](https://github.com/squidfunk/mkdocs-material/files/12786220/9.4.3-mike-path-prefix.zip)

##### Serving from a parent directory

1. Open `mkdocs.yml` and comment out

    ```diff
    -plugins:
    -  - info
    +#plugins:
    +#  - info
    ```

    to be able to actually build and not the reproduction.

1. Build the site:

    ```sh
    mkdocs build -d path/prefix/
    ```

1. Serve it using a simple static web server:

    ```sh
    python -m http.server
    ```

1. Open it in your browser at http://localhost:8000/path/prefix/.

1. Observe that the version selector is missing in the header bar, and observe in the browser's dev tools in the "Network" tab that the request

    ```
    GET http://localhost:8000/path/versions.json
    ```

    fails with HTTP status 404.

##### With `site_url` set

1. Comment in the line:

    ```diff
    -#site_url: http://localhost:8000/path/prefix/
    +site_url: http://localhost:8000/path/prefix/
    ```

    in `mkdocs.yml`

1. Serve the site:

    ```sh
    mkdocs serve
    ```

1. Open it in your browser at http://localhost:8000/path/prefix/.

1. Observe that the version selector is missing in the header bar, and observe in the browser's dev tools in the "Network" tab that the request

    ```
    GET http://localhost:8000/path/versions.json
    ```

    fails with HTTP status 404.

### Browser

_No response_

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

### PR DESCRIPTION
**Pull request by sisp**
I've fixed a bug related to using `mike` with path-prefixed builds. See #6123 for more details.

Fixes #6123.

### CODE REVIEW

**Comment by squidfunk** [comment]
Thanks for reporting. I'm not sure this does not break the usage without path prefix. We've had the version selector for quite a long time and adding the `../` is necessary for it to work. Could you please check if our demo repository still works with your change? https://github.com/squidfunk/mkdocs-material-example-versioning

Please also make sure it works when actually deployed to GitHub pages with mike.

**Comment by sisp** [comment]
I've deployed https://github.com/squidfunk/mkdocs-material-example-versioning both with current v9.4.3 and the version based on this PR:

- https://sisp.github.io/mkdocs-material-example-versioning-9-4-3/
- https://sisp.github.io/mkdocs-material-example-versioning-pr6124/

It seems you're right &ndash; v9.4.3 works fine on GitHub Pages and the version based on this PR does not. I might have misunderstood how `mike` works, particularly that it seems to be important to build the docs using `mike deploy` and not using `mkdocs build`, which is what I did in #6123. Can you confirm that's correct?

**Comment by squidfunk** [comment]
Converted to draft for the time the questions are unresolved.

**Comment by sisp** [comment]
> It sounds to me that there should be no difference in the output of `mike deploy` and `mike build`.

I was using `mkdocs build`, not `mike build`.

**Comment by sisp** [comment]
No problem. 🙂 Thanks for clarifying mike's behavior. 👍 Yes, I think we can close this PR.

**Pull request closed without merging**
