### PR TITLE
Update package metadata

### PR DESCRIPTION
**Pull request by ofek**
## Background

Hello there! The Python packaging ecosystem has standardized on the interface for build backends ([PEP 517](https://peps.python.org/pep-0517/)/[PEP 660](https://peps.python.org/pep-0660/)) and the format for metadata declaration ([PEP 621](https://peps.python.org/pep-0621/)/[PEP 631](https://peps.python.org/pep-0631/)). As a result, the execution of `setup.py` files is now [deprecated](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html).

So, I'm spending my free time updating important projects so that they are modernized and set an example for others 😄

## Summary of changes

This implements [PEP 621](https://peps.python.org/pep-0621/), obviating the need for `setup.py` and `MANIFEST.in`. The build backend `hatchling` (of which I am a maintainer in the [PyPA](https://github.com/pypa)) is now used as that is the default in the official [Python packaging tutorial](https://packaging.python.org/en/latest/tutorials/packaging-projects/). Hatchling is available on all the major distribution channels such as [Debian](https://salsa.debian.org/python-team/packages/hatchling), [Fedora](https://src.fedoraproject.org/rpms/python-hatchling), [Arch Linux](https://archlinux.org/packages/community/any/python-hatchling/), [conda-forge](https://anaconda.org/conda-forge/hatchling), [Nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/hatchling/default.nix), [Alpine Linux](https://github.com/alpinelinux/aports/blob/master/community/py3-hatchling/APKBUILD), [FreeBSD](https://github.com/freebsd/freebsd-ports/blob/main/devel/py-hatchling/Makefile)/[OpenBSD](https://github.com/openbsd/ports/blob/master/devel/py-hatchling/Makefile), [Gentoo Linux](https://github.com/gentoo/gentoo/tree/master/dev-python/hatchling), [MacPorts](https://github.com/macports/macports-ports/blob/master/python/py-hatchling/Portfile), [OpenEmbedded](https://github.com/openembedded/openembedded-core/commit/846e806181f1349be29cbce78c5041735dfd7e6f), [Spack](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-hatchling/package.py), [MSYS2](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-python-hatchling/PKGBUILD), etc.

## Notes

- The source distributions on PyPI are erroneously shipping a build artifact `*.egg-info` from `python setup.py develop`; this is now fixed

## Future

- We could ship optional wheels compiled with Mypyc, as Black [recently did](https://ichard26.github.io/blog/2022/05/31/compiling-black-with-mypyc-part-1/)

### CODE REVIEW

**Comment by squidfunk** [comment]
Thanks for providing the PR. My experience with Python package management hasn't been very good so far, so I'm pretty happy that it works right now. I understand that there's a new, canonical way of doing things, but before I can merge this, we really need to make sure that everything works as flawlessly as before. For example, does our [publishing workflow](https://github.com/squidfunk/mkdocs-material/blob/master/.github/workflows/publish.yml) still work? Does the Docker image still build?

I'm afraid I currently can't invest the time into getting this up and running, so if we decide to merge it, I will need some help from you or another collaborator to make this work. Are you interested in becoming a collaborator of this repository and maintain the new publishing workflow?

**Comment by ofek** [comment]
> maintain the new publishing workflow?

Yeah sure 👍

Simple tests though:

- Publish

```
❯ python -m pip install -q build
❯ python -m build
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (hatch-nodejs-version, hatch-requirements-txt, hatchling)
* Getting dependencies for sdist...
* Building sdist...
* Building wheel from sdist
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (hatch-nodejs-version, hatch-requirements-txt, hatchling)
* Getting dependencies for wheel...
* Building wheel...
Successfully built mkdocs_material-8.4.3.tar.gz and mkdocs_material-8.4.3-py3-none-any.whl
❯ ls dist
mkdocs_material-8.4.3-py3-none-any.whl
mkdocs_material-8.4.3.tar.gz
```

- Docker

```
❯ docker build -q -t mkdocs-material .
sha256:c402deafe151c2e2c39aa37ad28b56e953427c985b354ef6df56c6e7456044e6
```

**Comment by ofek** [comment]
Also:

> My experience with Python package management hasn't been very good so far

Yes, this was a justifiable common sentiment, which is why we standardized on things and are improving tooling 🙂

**Comment by squidfunk** [comment]
I've invited you as a collaborator. You should now be able to merge your changes when you're sure that the publishing workflow works. Note that we're currently using `twine`. I'm not whether this still works:

https://github.com/squidfunk/mkdocs-material/blob/b344ae8836fbdd47d5e83dd3c1d07a38ca11d94d/.github/workflows/publish.yml#L58

**Comment by ofek** [comment]
Accepted! Yes it still works. The only difference is that the `dist/*.tar.gz` and `dist/*.whl` files are now built by Hatchling rather than setuptools.

**Comment by squidfunk** [comment]
Okay, great, thanks! I'm not seeing how the version is deduced – previously, the version was loaded from `package.json` and injected into `setup.py`. How does hatch know which version is built?

**Comment by ofek** [comment]
A plugin https://github.com/agoose77/hatch-nodejs-version

**Comment by squidfunk** [comment]
Ah, nice! Sorry if my questions are stupid, I'm, not familiar with hatch. So from what I understand, this is ready for merging and should not lead to interruptions in publishing workflows? Sorry if I appear too protective, it's just that it took me some time to get this up and running. Publishing Node.js packages is so much easier.

**Comment by ofek** [comment]
No worries, I'm also not familiar with all the Hatch plugins now in existence 😄 

Yup ready for merge!

**Comment by ofek** [comment]
Also if you have time, a per-project upload token is recommended https://pypi.org/help/#apitoken

**Comment by squidfunk** [comment]
> Also if you have time, a per-project upload token is recommended https://pypi.org/help/#apitoken

Already set that up because Material for MkDocs was appointed the status of _critical project_, which made this mandatory:
https://twitter.com/squidfunk/status/1545506327903993860

**Comment by ofek** [comment]
Ah, in that case no need for `secrets.PYPI_USERNAME`, can just hard code `__token__`

**Comment by squidfunk** [comment]
Hmm, interesting. Switching to the new method seems to have destroyed the "used by" statistics:
Bildschirmfoto 2022-09-11 um 11 53 01

There were more than 15k, now there are 2. I think this is worth reporting to GitHub.

**Comment by squidfunk** [comment]
@ofek I'm going to temporarily revert this PR. The reason is that I don't feel comfortable with switching the build process to something I don't currently understand (haven't had the time to investigate). It doesn't only affect this repository, but also Insiders, for which it may have unforeseen consequences. Furthermore, I really don't like that the "used by" view is broken, as it signals the wrong thing (no adoption), which might be bad for the project.

**Comment by ofek** [comment]
I see, you just need:

- https://sethmlarson.dev/blog/preparing-for-the-wave-of-open-source-funding#dependency-chain-metadata
- https://github.com/urllib3/urllib3/blob/main/setup.py

**Comment by ofek** [comment]
I'll copy what others are doing to work around the Dependabot issue 👍

**Comment by ofek** [comment]
https://github.com/squidfunk/mkdocs-material/pull/4341

**Pull request merged**
