### PR TITLE
Adds mkdocs-awesome-pages-plugin to Dockerfile 

### PR DESCRIPTION
**Pull request by tdstein**
This change adds the [`mkdocs-awesome-pages-plugin`](https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin) to the Dockerfile.

We are using `mkdocs-material` extensively for [LifeOmic's Precision Health Cloud](https://docs.us.lifeomic.com/) documentation. Our build process consumes the official [docker image](https://hub.docker.com/r/squidfunk/mkdocs-material). Our site is getting rather complex, and we would like to add the `mkdocs-awesome-pages-plugin` to help simplify the management of large directories. Adding this plugin to the `mkdocs-material` Docker image is the simplest path forward.

### CODE REVIEW

**Comment by squidfunk** [comment]
Thanks for the PR! I've never used this plugin before and have heard of it quite recently but some people seem to use it. However, from what you added to the documentation I see no use case how to use it with the theme. We shouldn't discuss all options or mirror the whole documentation on all available options, but a little guidance to set it up would be great.

Additionally, I would kindly ask you to submit your PR to the `refactor/rxjs-typescript` branch, as we won't be doing another release on the 4.x branch which means the Docker image wouldn't get updated. The plugin documents have a slightly different internal structure and try to be more informative (especially for search), so it would be great if you could adhere to the new format.

**Comment by squidfunk** [comment]
I haven't checked - how much does the Docker image increase in size?

**Comment by tdstein** [comment]
No change in size:

```
rxjs-typescript              latest              60efefdd932e        About a minute ago   213MB
mkdocs-awesome-pages-plugin  latest              a5f79296a7a8        5 minutes ago        213MB
```

**Comment by tdstein** [comment]
The `mkdocs-awesome-pages-plugin` Python package is 60K

**Comment by squidfunk** [comment]
That sounds very reasonable, LGTM!

**Comment by tdstein** [comment]
🎉 Thanks for the quick review!

**Comment by squidfunk** [comment]
Note that the Docker image will be updated with the next release, which is either RC 4 or the final release.

**Comment by tdstein** [comment]
That works for me! I'm going ahead and testing out RC3 with our site. I will let you know if I run into any issues.

**Comment by tdstein** [comment]
Hey @squidfunk - I wanted to follow up and let you know that we are running v5.0.0 in production. Everything looks great!

[https://docs.us.lifeomic.com/](https://docs.us.lifeomic.com/)

**Comment by squidfunk** [comment]
@tdstein that's awesome!

**Pull request merged**
