### PR TITLE
Add title attribute to social links

### PR DESCRIPTION
**Pull request by Stanzilla**

### CODE REVIEW

**Comment by squidfunk** [comment]
There's actually no more `social.type` option and I think we shouldn't add one just for the sake of a title. I understand that optimizing for Lighthouse is a thing, but it would mean that the author would have to provide an explicit title for every link. What about adding `aria-hidden`?

**Comment by Stanzilla** [comment]
Hrm does that add a hover tooltip?

**Comment by Stanzilla** [comment]
I honestly don't quite like that change to icon formats, would it be a lot of work to allow the old scenario to work again?

**Comment by squidfunk** [comment]
> I honestly don't quite like that change to icon formats, would it be a lot of work to allow the old scenario to work again?

What exactly don't you like about it?

**Comment by Stanzilla** [comment]
That I lose access to the name variable, I would love to have URL, icon and name available as variables.

**Comment by squidfunk** [comment]
Suppose we introduce a `name` variable - what is the default if somebody doesn't provide it?

**Comment by Stanzilla** [comment]
Can we no longer deduct the name from the icon file name?

**Comment by squidfunk** [comment]
Yes, we could introduce a `name` member for `config.extra.social.*` and use that as a title, but then we have to think about what we use as a name when the author doesn't provide one.

**Comment by Stanzilla** [comment]
the svg file name?

**Comment by squidfunk** [comment]
bfea3315 automatically extracts the domain part from the URL – IMHO this is a better solution than to ask the author to provide a description for every link – does this solve your problem?

Ohne Titel

**Comment by Stanzilla** [comment]
Certainly helps, will get back to you if I need more, thanks!

**Comment by Stanzilla** [comment]
@squidfunk This is not good enough for Lighthouse (https://web.dev/link-name/?utm_source=lighthouse&utm_medium=devtools) want a new issue?

**Comment by squidfunk** [comment]
How is this not good enough? I thought we fixed this?

**Comment by Stanzilla** [comment]
image

**Comment by squidfunk** [comment]
I see, not fixable. We would have to introduce a new option to the social icons to set a name for each link. That’s impractical, do I would disregard Lighthouse recommendations in this case.

**Comment by Stanzilla** [comment]
Why not make the option optional?

**Comment by squidfunk** [comment]
We could but improving blindly for Lighthouse is no path I want to follow.

**Comment by Stanzilla** [comment]
Well people being able to add a little more descriptive texts to their social links would be nice, ignoring Lighthouse for now.

**Comment by squidfunk** [comment]
Yes, but then there will be other requests for even more possible customizations At other places. We have to cut at some point. You forked the theme, so it should be no problem to add it in your fork if desired.

**Comment by squidfunk** [comment]
... you‘re (currently) the only one who wants this feature

**Pull request closed without merging**
