### PR TITLE
Mention config iheritance for social cards

### PR DESCRIPTION
**Pull request by PEZ**
Hello, I think it is good to know of the config inheritance option when setting up social cards. So I added a few words and links about it.

### CODE REVIEW

**Comment by squidfunk** [comment]
Thanks! However, I'd find it to be confusing in this section. The Insiders installation guide includes a [section on configuration inheritance](https://squidfunk.github.io/mkdocs-material/insiders/getting-started/#built-in-plugins), which IMHO is a better place, as we now have several Insiders-only plugins.

**Comment by PEZ** [comment]
Yes, I do link to that section. Basically I just want to help people avoid the mental trap I got caught in trying to solve my use case with that ENV thing.

I now made another attempt that possibly is less confusing. You think that is better? Or is it better to not mention this option at all, maybe?

**Comment by squidfunk** [comment]
Let me think about this and come back to you. I'm in the process of doing a minor docs restructuring, so maybe I can come up with a better place than the one you suggested, but let's see. In general, I try to balance reading flow with the locality of information, which is always hard. It's not possible to have all information local.

**Comment by PEZ** [comment]
Cool. I agree it is a trade-off between flow and offering enough help for enough user types.... I'm taking the opportunity to learn from how you reason around issues like this.

**Comment by squidfunk** [comment]
Superseded by 27efd1dd6.

**Pull request closed without merging**
