### PR TITLE
Update setting-up-navigation.md

### PR DESCRIPTION
**Pull request by IcebergVerse**

### CODE REVIEW

**Comment by IcebergVerse** [comment]
icebergverse:patch-1

**Comment by squidfunk** [comment]
Thanks for the PR. However, it makes no sense, since it's incorrect English, or am I missing something?

**Comment by squidfunk** [comment]
Closing as non-sensical.

**Comment by IcebergVerse** [comment]
gh pr checkout 4589

**Comment by IcebergVerse** [comment]
`icebergverse:patch-1`
Update setting-up-navigation.md #4589

**Pull request closed without merging**
