### PR TITLE
add Simplified Chinese translation

### PR DESCRIPTION
**Pull request by cxlwill**

### CODE REVIEW

**Comment by squidfunk** [comment]
Thanks! However, please make your changes in the `src` directory. The `material` directory is overwritten on every build.

**Comment by squidfunk** [comment]
Is the language `zh` the correct identifier? I thought `cn`? Sorry, I'm not an expert in chinese ;-)

**Comment by martinbira** [comment]
Language is `zh` general for China. You actually have a few different variants when dealing with both languages and locales. I think that zh_CN is the Simplified version, zn_TW is Traditional and zh_HK is Hong Kong.

**Comment by cxlwill** [comment]
Yeah, I agree with @martinbira . Generally All Chinese is under `zh`. I'm not sure that sub-locale is allowed. If so, I can add  Traditional Chinese as well.

**Comment by squidfunk** [comment]
Thanks for both translations, really awesome. However, the locale format `zh_CN` is not supported by HTML5, as this is the value that is inserted into the `html` tag. Can we switch to the valid/accepted codes? See https://www.w3schools.com/tags/ref_language_codes.asp

**Comment by squidfunk** [comment]
... so we could offer the default (simplified?) under `zh` and traditional under `zh-Hant`.

**Comment by cxlwill** [comment]
I agree with you.

**Comment by squidfunk** [comment]
If you make the changes in the `language` attribute, I will merge your PR.

**Comment by cxlwill** [comment]
Yeah, I set Simplified Chinese to `zh` and Traditional Chinese to `zh-Hant`, at filename and inner name.  I think everything is OK now.

**Comment by jfcherng** [comment]
I have some words to say about this PR.

- The words chosen in that translation is for people who live in China. For example, Taiwanese doesn't use `搜索` and we use `搜尋` instead. But I know that zh-Han`t` is for Traditional, not for Taiwan. Would it possible to create variant as @martinbira said: `zh-TW`, `zh-HK` etc...?

- The translation `"clipboard.copied": "粘贴",` is shown when a visitor click the "copy-to-clipboard" button on a code block. It should be translated into `已复制(already copied)` rather than `粘贴(paste)`.

**Comment by martinbira** [comment]
Probably not a bad idea if possible. When I worked with translations for the Sony Mobile web we hade zh-cn, zh-tw, and zh-hk as different versions of Chinese.

**Comment by squidfunk** [comment]
`zh-TW` is not a valid code for the `lang` attribute of the `html` tag, see https://www.w3schools.com/tags/ref_language_codes.asp

**Comment by cxlwill** [comment]
@martinbira Chinese language code for HTML keeps changing these years. It used to be zh-Cn kind of thing, which depends on users' locale. For lates zh-Hans kind, it consider language itself despite of using locale. So the connection looks like below:

- zh-CN → zh-CHS → zh-Hans → zh → Invariant
- zh-TW → zh-CHT → zh-Hant → zh → Invariant

**Comment by cxlwill** [comment]
@jfcherng Actually I struggled about 搜索(search) and 搜尋(search) for quite a while. Do HKer use latter as well? I will change `already copied`, since it is purely my mistaken.

**Comment by jfcherng** [comment]
@cxlwill I am not a HKer but I guess yes because both `yahoo.com.hk` and `google.com.hk` use `搜索`.

**Comment by squidfunk** [comment]
Awesome work guys, thanks!

**Pull request merged**
