### PR TITLE
Fix inline line highlight padding, wrapping, and gutter background

### LINKED ISSUE #1499: Code block styling issues with pymdownx.inline and inline
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

Issue with 5RC1 inline line highlighting.  Support for inline highlighting is a little broken. Particularly my interest was in support for `pymdownx-inline`, but I've generally investigated and made normal inline also look the same (whether we want to actually do anything with that is up to you).

1. Background is transparent, so when scrolling content underneath, the code shows through.
2. Margins and such are not right with recent changes.
3. Line highlight wraps to next line.
4. Highlight padding is different between table and inine styles, but only table inline padding is used causing inilne code with highlights to have scrollbars.

This was discussed in Gitter.

Fixes here: https://github.com/facelessuser/pymdown-extensions/blob/master/docs/src/scss/_code.scss

Note:

1. Highlight fix is here: https://github.com/facelessuser/pymdown-extensions/blob/master/docs/src/scss/_code.scss#L29 and here: https://github.com/facelessuser/pymdown-extensions/blob/master/docs/src/scss/_code.scss#L78. You could also just make them the same padding and have universal padding.
2. Normal inline consistency changes are here: https://github.com/facelessuser/pymdown-extensions/blob/master/docs/src/scss/_code.scss#L35
2. Pymdownx-inline fixes are here: https://github.com/facelessuser/pymdown-extensions/blob/master/docs/src/scss/_code.scss#L56

"Special" css can be ignored unless you wish to support pygments special class attached to line numbers.

### Expected behavior

Inline, especially with line highlighting, doesn't quite look right.

### Actual behavior

See description

### Steps to reproduce the bug

1. ...
2. ...
3. ...

### Package versions

* Python: Any
* MkDocs: Latest
* Material: 5.0.0rc1

### Project configuration

I use `pymdownx-inline` with line numbers though I believe there are issues with normal `inline` as well.

### System information

* OS: Any
* Browser: Any

### PR DESCRIPTION
**Pull request by facelessuser**
- Line highlight pad should match the parent
- Float the gutter left to force code and numbers not to wrap
- Provide a background for the gutter

Fixes #1499

### CODE REVIEW

**Comment by facelessuser** [comment]
How do you want to handle the coloring of the gutter background? I basically eye balled it, but it would be nice to derive it

**Comment by squidfunk** [comment]
> How do you want to handle the coloring of the gutter background? I basically eye balled it, but it would be nice to derive it

That is a good question, as the code background has alpha transparency which will not have the intended effect when used on the line numbers. I think we should switch to an opaque background. I removed code background in admonition titles in a recent commit, so I think the transparency is of no use anymore, or am I missing something?

**Comment by facelessuser** [comment]
Results:

aZUgB9HVus

**Comment by squidfunk** [comment]
Thanks for providing the visual aid. Unfortunately the gutter doesn't match the background color, but that should be resolved when switching to opaque colors and CSS variables.

**Comment by facelessuser** [comment]
Root level, stretched code blocks use a different padding, so we have to stretch the highlighting differently for this that case as well. Last commit accounts for this case.

**Comment by facelessuser** [comment]
Sorry for the churn, but I think I got them all:

7kV0SLCo7E

**Comment by squidfunk** [comment]
LGTM, thanks for taking the time to investigate and fix this!

**Pull request merged**
