### PR TITLE
Upgrade to Mermaid 10.6.1

### PR DESCRIPTION
**Pull request by lambda**
Bump the version of Mermaid up to 10.6.1. Per the release notes at https://github.com/mermaid-js/mermaid/blob/develop/CHANGELOG.md the render function is async now, so update to the new async render function.

There's also apparently a change to use ESM, but I didn't seem to have any trouble with just bumping the version and updating it to use async. It looks like it's working without any change to how we load it, but I'm not much of a frontend developer so I could be missing something.

### CODE REVIEW

**Comment by mampersat** [comment]
+1

**Comment by lambda** [comment]
@manselmi Rebased and updated to pull in 10.6.1

@squidfunk Looks like you're aware of this, are there any concerns that I should address? It should be fairly easy to test out. I saw the discussion about ESM on on other PRs, but there didn't seem to need to be any updates to how this was loaded, and it works in the browsers I have tested. I don't have any older browsers easily available to test against.

**Comment by squidfunk** [comment]
Thanks for the PR! As mentioned in https://github.com/squidfunk/mkdocs-material/issues/5758#issuecomment-1792078444, I need some time to test this thoroughly. I'm currently focusing on #6307, but as soon as we have a first prototype deployed, I'll take some time to revisit this PR ☺️

**Comment by squidfunk** [comment]
So, thanks for your work! This PR looks good, and my testing shows everything we supported up to now is still supported. New diagram types might need additional styles for better integration, so PRs welcome.

**Pull request merged**
