### PR TITLE
add support for multiple default aliases in version warning

### PR DESCRIPTION
**Pull request by SaltyAimbOtter**
This PR adds the ability to define not only one but multiple default version aliases that hide the version warning.

## Docs Changes Preview
grafik

## Context
This is related to #4919: After opening the issue, our project members had an internal discussion. I will post our conclusions in the issue shortly after opening this PR.

Please excuse any mistakes regarding the tooling, I'm new to web development.

### CODE REVIEW

**Comment by squidfunk** [comment]
Thanks for the PR! We should allow both syntaxes, a string value and a list to allow, as it's a much more natural syntax to define it as a list in YAML. Judging from the [current implementation](https://github.com/squidfunk/mkdocs-material/blob/e496f77b6ce5febc448345cb8a0d7af594627300/src/base.html#L386), this should work out-of-the-box from a template perspective, and only needs adjustment in the JavaScript. We could then do this:

``` yaml
extra:
  version:
    default: stable
```

... as well as:

``` yaml
extra:
  version:
    default:
      - stable
      - development
```

What needs to be adjusted is the logic here – we now need to handle strings as well as arrays of strings:
https://github.com/squidfunk/mkdocs-material/pull/4976/files#diff-dfd2137f020c891f8ca6ca734202c930b2008ace56b84bc0cd6f61ed7c33c0dcL162

Also note that your PR contains too many files. You somehow committed the files that are generated during development, as well as the files that are generated by the build, e.g. `search.js` and `search.********.js`. Pleae make sure to exclude the former from the PR.

---

If you feel that this is too much to handle, I can take care of it when I find some time 😊

**Comment by SaltyAimbOtter** [comment]
I'm totally lost 🙈 
I managed to develop the change but I have no idea how to build the theme the right way. Therefore I have stripped this branch of all the dev stuff and just included the changes. Please checkout the branch and do whatever magic is required 🧙

**Comment by SaltyAimbOtter** [comment]
Hey Martin,
I think something with your build tools is broken. I have asked a few friends with more experience with the tools at hand but none of them could get it to work. 

When running `npm run build`, the css files `main`, `palette`, `custom` all contain absolute paths instead of relative ones like before the build:
`src/.overrides/assets/stylesheets/custom/_typeset.scss` becomes:
`file:///C:/Users/CyberOtter/IdeaProjects/mkdocs-material/src/.overrides/assets/stylesheets/custom/_typeset.scss`.

Other than that it seems do everything right, e.g. replacing / renaming `custom.acd3711.min.js` with `custom.317484c8.min.js` based on the new hash of the file.

I have tried building with IntelliJ's and VSCode's terminals and from both Windows and WSL.
node: `v18.12.0`
npm: `9.4.2`

**Comment by squidfunk** [comment]
Thanks for noting. I don't have a Windows machine at my disposal, so any help on this is appreciated. We need to make sure that it runs on Linux, macOS and Windows, but I can only test for the two former.

**Comment by SaltyAimbOtter** [comment]
@seyfahni build this on Linux for me. It should be good to merge now.

 It seems like `build:all` is required for a PR? If we run just build too many files get deleted. Perhaps you should add some "participating" documentation for contributors like you did for issues.

**Comment by squidfunk** [comment]
Please give me some more time to look into this.

**Comment by squidfunk** [comment]
So, thanks again for your work on this! I've taken your work and refactored it a little. Additionally, I've added the ability to provide regular expressions as default versions. This should allow for even greater flexibility, as you could now tag version aliases with suffixes or prefixes to identify stable versions:

``` yaml
extra:
  version:
    provider: mike
    default:
      - '-dev$' 
      - ...
```

Regular expression support is highly experimental, which is why it's not yet documented. Let's first give it a try and see if we can consider it useful enough. Superseded by b25723571. I've added you as a co-author.

**Pull request closed without merging**
