### PR TITLE
Support for Referrer-Policy metadata

### PR DESCRIPTION
**Pull request by LucidOne**
Provide a means of setting `referrerpolicy` attribute via metadata.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

_mkdocs.yml_:
```
extra:
  referrer: same-origin
```

### CODE REVIEW

**Comment by squidfunk** [comment]
Thanks for the PR. With 5.5.0, we have [deprecated several metadata flags](https://squidfunk.github.io/mkdocs-material/deprecations/), including redirects, as the recommended way now is to extend the theme. There are just too many `meta` tags that we would need to provide all of them via extra variables. Theme extension is very easy.

As an example see the [Open Graph and Twitter Cards](https://squidfunk.github.io/mkdocs-material/reference/meta-tags/#customization) guide, which both use this mechanism.

**Comment by LucidOne** [comment]
That's not unreasonable and locally I'm extending the theme, but maybe it would make more sense to loop through a dict in the template to generate all the meta attributes?

**Comment by squidfunk** [comment]
The Problem is that some meta attributes are set  is more complex logic than plain assignment. See the `base.html` template for some examples.

A second downside of setting it via `mkdocs.yml` is that you can only set them once, side-wide, whereas with theme extension you can set it per-document, if desired.

**Comment by LucidOne** [comment]
Should I reformat this as an example in the docs?

**Comment by squidfunk** [comment]
I generalized the meta tags documentation in c09e5f1c and added Twitter Cards and Open Graph as an example. `Referrer-Policy` albeit useful, is rather rarely used, so we'll leave it at that, as we cannot add every possible meta tag to the documentation.

**Pull request closed without merging**
