### PR TITLE
Feature/how to GitHub

### PR DESCRIPTION
**Pull request by Andre601**
Implements the Tutorial about how to use GitHub Pages with MkDocs and MkDocs-Material.

I created a tutorials folder for the other planned tutorials (#1573) and integrated the github-pages,md file as follows to the nav:
```yaml
nav:
  # Other paths up to Plugins
  - Tutorials:
    - GitHub Pages: tutorials/github-pages.md
  # Releases and other paths.
```

### CODE REVIEW

**Comment by squidfunk** [comment]
Thanks for the first draft! It's basically good but could use some work in regard to language 😊. I just created a new branch called `docs/tutorials` where I added the tutorials section. Could you PR to the new branch? We could then merge it immediately and other people (i.e. native speakers, technical writers) could improve the language and writing.

**Comment by Andre601** [comment]
I think you could edit the target branch to be the tutorial one (if file/location remains the same that is...

**Comment by squidfunk** [comment]
Could you resolve the conflicts?

**Comment by Andre601** [comment]
What exact conflicts?
I don't see any here... (At least GitHub doesn't tell me of any)

**Comment by Andre601** [comment]
There we go.
I'm also always happy over grammar corrections, as I'm not a native English speaking person (And Grammarly isn't always helping xP)

**Comment by squidfunk** [comment]
Great, thanks! We can always improve later, it’s great to have a starting point 😊

**Pull request merged**
