### PR TITLE
Documented the displaying of metadata in page body

### PR DESCRIPTION
**Pull request by vedranmiletic**
Hopefully this is another useful addition to the documentation.

### CODE REVIEW

**Comment by squidfunk** [comment]
Thanks for the PR! I see two issues with this:

1. It should go under the __customization__ section, because it involves theme extension.
2. Could you come up with a simpler example that doesn't involve so many lines? This would make it easier for users to grasp, which will reduce maintenance on my side.

**Review by squidfunk — CHANGES_REQUESTED** [review]
See above.

**Comment by vedranmiletic** [comment]
I can reduce the example, but add a warning admonition that directs the user to copy the contents of the block from `main.html` and then modify it in order to keep all the features of theme. Would that be acceptable?

**Comment by squidfunk** [comment]
Another idea might be to just extend the content block and put stuff at the bottom. It might not be perfect, but it's easier to understand, like so:

``` jinja
{% block content %}
  {{ super() }}
  <!-- ... your additions ... -->
{% endblock %}
```

**Comment by vedranmiletic** [comment]
Neat! Didn't know that trick. Let's do it like that then.

**Comment by squidfunk** [comment]
LGTM, thanks!

**Comment by vedranmiletic** [comment]
@squidfunk Was this intentionally removed from the docs? I think it's still an useful addition and doesn't duplicate the instructions in [metadata in headers section](https://squidfunk.github.io/mkdocs-material/reference/#using-metadata-in-templates).

**Comment by squidfunk** [comment]
Yes, the meta tags reference page was moved to the beginning of the reference. The new [Using metadata in templates](https://squidfunk.github.io/mkdocs-material/reference/#using-metadata-in-templates) explains how to use custom front matter in templates, which is exactly what this PR included, albeit it's another example.

**Comment by vedranmiletic** [comment]
The idea was to demonstrate how to display the metadata *in the page body*, not the header. It also showed how to use the `super()` so I don't think it's redundant for non-experts (your perspective as the author of the project who is very familiar with the code is understandably different).

**Comment by squidfunk** [comment]
I understand the different use cases, but as it uses exactly the same principles, namely theme extension and template overrides, I'm considering those the same. I really don't want to provide redundant information, because it blows up the docs. If more users have trouble with this, I will reconsider adding it back to the docs.

**Pull request merged**
