### PR TITLE
Escape html in header title

### PR DESCRIPTION
**Pull request by timpharo**
## Expected Behaviour
When adding a html tags to H1's in markdown files, such as Font awesome icons, the html title should strip the html and therefore display the title text only

## Current Behaviour
Adding html to H1's in markdown files is displayed unescaped in the title

## Possible Solution
Stripping all html when reading the property in as a Jinja template.  This PR addresses the issue in this way.

## Steps to Reproduce
1. Add `fontawesome_markdown` extension and `awesome-pages` plugin
2. Add Font Awseome icon to any .md file
3. Navigate to the page you have edited 
4. The page title, also displayed as the tab title, contains the unescaped html

### CODE REVIEW

**Comment by timpharo** [comment]
Thanks again

**Comment by timpharo** [comment]
I know you have just done a release for my last PR, but is there an ETA on this being released as it would be great to tackle all my issues with one upgrade

**Comment by squidfunk** [comment]
I'm actually waiting for you to find more bugs ;-) If you think that there should be no more necessity for `striptags`, I can do a release tomorrow.

**Comment by timpharo** [comment]
I'll retire from striptags for now an maybe find a new focus :-) I should have mentioned on the first fix that i knew of another one, but forgot. Whenever you have time, just thought I would ask +1

**Comment by squidfunk** [comment]
Released as part of 4.4.2. Sorry for the delay.

**Pull request merged**
