### PR TITLE
Add missing gitlab pages in nav and mention GitHub template

### PR DESCRIPTION
**Pull request by Andre601**
Adds the GitLab pages tutorial to the nav in the mkdocs.yml (Was missing) and also mentions the template I made for using MkDocs with GitHub pages.

### CODE REVIEW

**Comment by squidfunk** [comment]
Thanks for the PR. However I think we should rather consider adding an `examples` directory to this repo as opposed to linking too many downstream repos, which become out of date more quickly.

**Comment by Andre601** [comment]
> Thanks for the PR. However I think we should rather consider adding an `examples` directory to this repo as opposed to linking too many downstream repos, which become out of date more quickly.

Would be an idea, even tho the chance that a Repo becomes "outdated" would imo be a fairly small one.
Imo could we just note, that the linked repository is not maintained by you and therefore could be outdated.

Additionally should we then also alter the gitlab tutorial as it also mentions a template that can be used.

**Comment by squidfunk** [comment]
> Would be an idea, even tho the chance that a Repo becomes "outdated" would imo be a fairly small one. Imo could we just note, that the linked repository is not maintained by you and therefore could be outdated.

As a background: I'm currently evaluating the survey data and think of restructuring the docs a bit with more examples and a clearer configuration guide, which is why I think integrating it directly into the repository is more natural.

> Additionally should we then also alter the gitlab tutorial as it also mentions a template that can be used.

Yes, I'd also favor this as an example. This could be a good addition to the tutorial section.

**Comment by Andre601** [comment]
I updated the PR to now only update the navigation to add the GitLab page.

I'll later make a PR improving the GitHub Page as I discovered that you don't need a PAT to push changes to the gh_pages branch.

**Comment by squidfunk** [comment]
Thanks!

**Pull request merged**
