### PR TITLE
Fix indentation complaints

### PR DESCRIPTION
**Pull request by nebulade**
not entirely sure why I hit this, however a build from master does not work due to the indentation complaints:

```
src/assets/javascripts/application.js
  139:1  error  Expected indentation of 6 spaces but found 8    indent
  140:1  error  Expected indentation of 6 spaces but found 8    indent
  153:1  error  Expected indentation of 6 spaces but found 8    indent
  154:1  error  Expected indentation of 6 spaces but found 8    indent
  162:1  error  Expected indentation of 8 spaces but found 10   indent
  163:1  error  Expected indentation of 8 spaces but found 10   indent
  194:1  error  Expected indentation of 4 spaces but found 6    indent
  195:1  error  Expected indentation of 6 spaces but found 8    indent
  196:1  error  Expected indentation of 4 spaces but found 6    indent
  197:1  error  Expected indentation of 6 spaces but found 8    indent
  198:1  error  Expected indentation of 8 spaces but found 10   indent
  199:1  error  Expected indentation of 10 spaces but found 12  indent
  200:1  error  Expected indentation of 10 spaces but found 12  indent
  201:1  error  Expected indentation of 8 spaces but found 10   indent
  202:1  error  Expected indentation of 6 spaces but found 8    indent
  203:1  error  Expected indentation of 2 spaces but found 4    indent

✖ 16 problems (16 errors, 0 warnings)
  16 errors, 0 warnings potentially fixable with the `--fix` option.
```

If this is not the correct fix or simply an issue on my end, please close the pull request.
Still would be interesting to know what could trigger this in such a case.

### CODE REVIEW

**Comment by squidfunk** [comment]
I believe this has to do with the new version of ESLint that got released. The dependencies are locked through `yarn`, and Travis uses `yarn`, so the build environment works. You almost certainly installed with `npm install`. However, I cannot merge this PR as it includes non-minified code in the `material` folder. I will issue a separate PR to fix the ESLint warnings.

**Comment by nebulade** [comment]
Thanks for the explanation, I did install with `npm install`.
For the future, is there a documentation for how to install and build the project cleanly as well as prepare a clean pull request?

**Comment by squidfunk** [comment]
Yes there is: http://squidfunk.github.io/mkdocs-material/customization/#theme-development
Feel free to PR anything that is missing in the docs if you encounter something.

BTW: I believe this is a fix for a regression in ESLint, because I remember that the indentation needed to be fixed before, so now it looks more natural.

**Comment by squidfunk** [comment]
Fixed in #423

**Pull request closed without merging**
