### PR TITLE
Support the Google analytics 4

### PR DESCRIPTION
**Pull request by cainmagi**
Currently, the theme does not support the newest Google analytics 4 API. I provide an option for enabling it in the config file. In `mkdocs.yml`, add the following line:

```yaml
# Google Analytics
google_analytics_4:
  - <your-google-analytics-4-ID>
```

When setting `google_analytics_4`, the original configs `google_analytics` would not be used.

### CODE REVIEW

**Comment by squidfunk** [comment]
Thanks for your pull request. I'm sorry, but I have to ask: have you tested this code? I'd be surprised if it worked, because in general, `mkdocs.yml` doesn't allow for adding custom code to the top-level of the configuration file. Everyting custom needs to be added to `theme.*` or `extra.*`, which is also the reason why this hasn't been addressed yet, as this would mean redundant configuration.

There are several issues here that discuss GA4 / GTAG. In essence, we'd need to wait for https://github.com/mkdocs/mkdocs/issues/2252 to be merged.

**Comment by cainmagi** [comment]
> Thanks for your pull request. I'm sorry, but I have to ask: have you tested this code? I'd be surprised if it worked, because in general, `mkdocs.yml` doesn't allow for adding custom code to the top-level of the configuration file. Everyting custom needs to be added to `theme.*` or `extra.*`, which is also the reason why this hasn't been addressed yet, as this would mean redundant configuration.
> 
> There are several issues here that discuss GA4 / GTAG. In essence, we'd need to wait for [mkdocs/mkdocs#2252](https://github.com/mkdocs/mkdocs/issues/2252) to be merged.

Thank you! Actually, I am not very familiar with this theme. However, today I use my modification to create a new GA4 application, and I could confirm that this modification works on my website:

image

I am just following your instructions on [this page](https://squidfunk.github.io/mkdocs-material/creating-your-site/). The modified `mkdocs.yml` locates in the root path of my source folder.

```
.
├─ docs/
│  └─ index.md
└─ mkdocs.yml
```

If you feel that my implementation has mistakes, you could close this this issue. I am looking forward to see an official implementation for supporting GA4.
Thank you!

**Comment by squidfunk** [comment]
Thanks for responding so quickly. I'd rather wait for the PR to be merged which will deprecate the current GA implementation. When this is released, we can add support for GA4, as well as GTAG.

**Comment by cainmagi** [comment]
> Thanks for responding so quickly. I'd rather wait for the PR to be merged which will deprecate the current GA implementation. Your implementation is non-standard in respect to MkDocs and may have unintended consequences. When this is released, we can add support for GA4, as well as GTAG.

I understand. Thank you!

**Comment by squidfunk** [comment]
`gtag.js` support just landed in `master` and will be released soon. Feedback appreciated Now, both formats are supported.

__Google Analytics__

``` yaml
extra:
  analytics:
    provider: google
    property: UA-XXXXXXXX-X
```

__Google Analytics 4__ (via `gtag.js`)

``` yaml
extra:
  analytics:
    provider: google
    property: G-XXXXXXXXXX
```

**Comment by cainmagi** [comment]
Thank you! I will keep track of this.

**Comment by squidfunk** [comment]
As there was confusion among users whether this was already released - no, it's not part of 7.1.7. To test-drive the new analytics integration, install Material for MkDocs from git like so:

```
pip install git+https://github.com/squidfunk/mkdocs-material.git
```

**Comment by squidfunk** [comment]
7.1.8 was just released, which contains the changes.

**Comment by sorenwacker** [comment]
Is there a way to verify that this part is working? When I open the source code of the generated page, what element should I look for? I do not see the provided google ID anywhere. And google analytics also does not start tracking.

**Comment by sorenwacker** [comment]
Tried `mkdocs-material` 7.1.8 and 7.3.0 (?).

**Comment by squidfunk** [comment]
`analytics.js` should be loaded, see [this partial](https://github.com/squidfunk/mkdocs-material/blob/master/src/partials/integrations/analytics/google.html). I can verify that it works, so it might be related to your setup or your customizations, if any.

**Comment by sorenwacker** [comment]
Now it works. ;-)

**Pull request closed without merging**
