### PR TITLE
Fix issues related to latest Pygments and Pymdown Extensions

### PR DESCRIPTION
**Pull request by facelessuser**
Fixes remaining issues related to #3840

### CODE REVIEW

**Comment by facelessuser** [comment]
The environment would need to be rebuilt, I didn't want to commit all of that noise.

**Comment by squidfunk** [comment]
Thanks!

**Comment by squidfunk** [comment]
Unfortunately, there's still some work to do. Tables now have rounded borders in tabs because the hierarchy is entirely different. I need some more time to polish this and wrap it up, but it's tedious work.

**Comment by squidfunk** [comment]
I think I got all cases. There was some regression with rounded borders for full-width code blocks on mobile, and with code blocks nested under tabs. Fixes in bdb5ba5a3. I need to merge this into Insiders tomorrow, then I can issue a release.

Unfortunately, some selectors need to be overly specific.

**Comment by facelessuser** [comment]
Ah, yeah, I missed that apparently.

**Comment by squidfunk** [comment]
Let's hope the syntax doesn't change again. Code blocks and content tabs and their combinations are quite fragile 😅

**Comment by facelessuser** [comment]
Yeah, I hope they don't change again too. It caught me off gaurd.

**Comment by squidfunk** [comment]
Merge done. Also, https://github.com/squidfunk/mkdocs-material/commit/1eeb8b7c0ce30a2f3e1870e606be730d1fa3596a removes some more unnecessary stuff. I'll issue a release later or tomorrow.

**Pull request merged**
