### PR TITLE
Address Issue #1214: Allow primary colour black

### PR DESCRIPTION
**Pull request by timpharo**

### CODE REVIEW

**Comment by squidfunk** [comment]
Unfortunately, this will also render all links in black color, which makes them indistinguishable from body copy. This needs to be addressed in a similar manner as the `white` color which is a special case inside the `application-palette` file.

**Comment by squidfunk** [comment]
Took the time and fixed it in 6b7535b

**Comment by mightymackem** [comment]
If you select `black` as the primary color and want to use `light blue` as the color for links, is that possible? If so, what needs to change in the `application-palette.scss` to make this happen?

**Comment by squidfunk** [comment]
We can only set one link color per primary color, so no. I chose indigo as the link color as 1) it’s the default of this theme and 2) its similar to the default link color of all browsers. You could however set the link color yourself with one line of CSS. See the customization guide for guidance.

**Pull request closed without merging**
