### PR TITLE
Add Japanese translation

### PR DESCRIPTION
**Pull request by miyahan**
for #509 🍣

### CODE REVIEW

**Comment by squidfunk** [comment]
Thanks! I renamed the file to `ja.html`, because that's what the language code says, and strangely what the HTML5 docs say.

**Comment by miyahan** [comment]
Thanks!

I think so, too. However, When name `jp.html` to `ja.html`, I can not search Japanese (non-ASCII characters). Because, It requires lunr-languages, but `lunr.ja.js` does not exist in [1.0.0 release](https://github.com/MihaiValentin/lunr-languages/tree/1.0.0). Instead `lunr.jp.js` exists.

In the master branch, it was renamed to `lunr.ja.js`, and `lunr.jp.js` became an alias to it.  
(ref: [Change Japanese language code, jp into ja by fmy · Pull Request #33 · MihaiValentin/lunr-languages](https://github.com/MihaiValentin/lunr-languages/pull/33))

So, MkDocs Material must load `lunr.jp.js` when language set to `ja` until next release of lunr-languages...

**Comment by squidfunk** [comment]
I see the problem. For this reason theme language and search languages were separated again in 2.x. Please upgrade to 2.x and set the following:

```
theme:
  language: ja

extra:
  search:
    language: jp
```

**Comment by miyahan** [comment]
I read the [document](https://squidfunk.github.io/mkdocs-material/getting-started/#site-search) and set it as `extra/search/languages = jp`. I fixed it to `extra/search/language = jp` and I now can search Japanese. Thanks !!

**Comment by squidfunk** [comment]
No problem, it was an error in the documentation which I fixed a few minutes ago.

**Comment by squidfunk** [comment]
@miyahan could you provide a translation for "Skip to content"? Japanese is one of the languages missing 😊Just post it as a comment, I will integrate it.

**Comment by Stanzilla** [comment]
That's コンテンツにスキップ

**Comment by squidfunk** [comment]
I also tried Google translate and it returned exactly the same 😂

Bildschirmfoto 2020-03-05 um 14 28 53

**Comment by Stanzilla** [comment]
Hah, I actually went to https://www.w3.org/WAI/videos/standards-and-benefits/ja

**Comment by squidfunk** [comment]
Maybe @miyahan can shed some light on this.

**Pull request merged**
