### PR TITLE
Small change in Danish translation

### PR DESCRIPTION
**Pull request by cfaagaard**

### CODE REVIEW

**Comment by saltydk** [comment]
Should probably be 
```json
"readtime.other": "# minutters læsetid",
```

**Comment by squidfunk** [comment]
Thanks for the PR! So what's it gonna be? I'm not proficient in Danish 😉

**Comment by saltydk** [comment]
My suggestion is how we would write it in Danish when referring to multiple minutes, which I assume was the intent here.

**Comment by squidfunk** [comment]
Im not sure how to resolve this. If you both could please discuss what makes sense and we could reach a conclusion, that would be amazing @saltydk @cfaagaard

**Comment by saltydk** [comment]
My suggestion is the correct way if the intent is multiple minutes, which I assumed to be the case.

**Comment by squidfunk** [comment]
Thanks @saltydk! Since OP hasn't responded, we go with your suggested improvement. Added in 7fa5ea060, which supersedes this PR.

**Comment by cfaagaard** [comment]
Sorry. Been offline. I agree with @saltydk .

**Pull request closed without merging**
